name: hanini_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6
  
  # UI packages
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^1.0.0
  flutter_animate: ^4.5.2
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  lottie: ^2.1.0
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1
  
  # State management & utilities
  provider: ^6.0.5
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  url_launcher: ^6.1.8
  uuid: ^4.5.1
  intl: ^0.19.0
  
  # Storage & data
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # API & Network
  http: ^1.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  
  # Media & sensors
  camera: ^0.11.0+2
  just_audio: ^0.9.46
  speech_to_text: ^7.0.0
  noise_meter: ^5.0.2
  geolocator: ^13.0.2
  
  # Configuration
  flutter_dotenv: ^5.2.1
  
  # Realtime communication
  flutter_webrtc: ^0.9.48+hotfix.1
  
  # Localization
  localization: ^2.1.1

  # Pull to refresh
  pull_to_refresh: ^2.0.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  iconsax: ^0.0.8
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/credentials/
    - assets/services_icon/
    - assets/images/
    - assets/images/ads/
    - assets/animation/
    - assets/search_icons/
    - assets/animation/voice_wave.json
    - assets/animation/voice_wave2.json
    - assets/animation/processing.json
    - assets/animation/Animation - 1739443672393.json
